[package]
name = "dovi_meta"
version = "0.1.0"
edition = "2021"
authors = ["Rainbaby"]
rust-version = "1.64.0"
license = "MIT"
build = "build.rs"

[dependencies]
num-traits = "0.2.15"
num-derive = "0.3.3"

uuid = { version = "1.1.2", features = ["v4"] }

dolby_vision = "2.0.0"
# TODO: Use timecode as unique id, as an option.
#vtc = "0.1.9"
chrono = "0.4.22"
serde = { version = "1.0.144", features = ["derive"] }
serde-aux = "4.0.0"
quick-xml = { version = "0.26.0", features = ["serialize"]}

clap = { version = "4.0.18", features = ["derive", "wrap_help"] }
anyhow = "1.0.62"
itertools = "0.10.3"

[build-dependencies]
vergen = { version = "7.4.2", default-features = false, features = ["build", "cargo", "git"] }