[package]
name = "dovi_meta"
version = "0.1.0"
edition = "2021"
authors = ["Rainbaby"]
rust-version = "1.64.0"
license = "MIT"
build = "build.rs"

[dependencies]
num-traits = "0.2.15"
num-derive = "0.3.3"

uuid = { version = "1.1.2", features = ["v4"] }

dolby_vision = "3.1.2"
# TODO: Use timecode as unique id, as an option.
#vtc = "0.1.9"
chrono = "0.4.24"
serde = { version = "1.0.158", features = ["derive"] }
serde-aux = "4.0.0"
quick-xml = { version = "0.28.1", features = ["serialize"]}

clap = { version = "4.1.11", features = ["derive", "wrap_help"] }
anyhow = "1.0.70"
itertools = "0.10.5"

[build-dependencies]
vergen = { version = "7.5.1", default-features = false, features = ["build", "cargo", "git"] }